# Generated by Django 3.0.7 on 2020-06-29 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('email', models.EmailField(max_length=25, null=True, verbose_name='邮箱')),
                ('on_job', models.CharField(default='在职', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(choices=[('石家庄市', '石家庄市'), ('唐山市', '唐山市'), ('秦皇岛市', '秦皇岛市'), ('邯郸市', '邯郸市'), ('邢台市', '邢台市'), ('保定市', '保定市'), ('张家口市', '张家口市'), ('承德市', '承德市'), ('沧州市', '沧州市'), ('廊坊市', '廊坊市'), ('衡水市', '衡水市'), ('雄安新区', '雄安新区'), ('不区分', '不区分')], max_length=100)),
                ('acceptancedate', models.DateField()),
                ('intersectiondate', models.DateField()),
                ('opscontent', models.TextField(max_length=3000)),
                ('patrolrequire', models.TextField(max_length=500)),
                ('participants', models.CharField(max_length=50)),
                ('customer', models.CharField(max_length=20)),
                ('supervisor', models.CharField(max_length=20)),
                ('contactors', models.TextField(max_length=200)),
            ],
            options={
                'verbose_name': '项目列表',
                'verbose_name_plural': '项目列表',
            },
        ),
        migrations.CreateModel(
            name='OpsRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('客户致电', '客户致电'), ('主动发现', '主动发现'), ('合作单位致电', '合作单位致电'), ('内部支持', '内部支持')], max_length=15)),
                ('qcategory', models.CharField(choices=[('技术支持', '技术支持'), ('故障处理', '故障处理'), ('问题咨询', '问题咨询'), ('商务售前支撑', '商务售前支撑')], max_length=10)),
                ('area', models.CharField(choices=[('石家庄市', '石家庄市'), ('唐山市', '唐山市'), ('秦皇岛市', '秦皇岛市'), ('邯郸市', '邯郸市'), ('邢台市', '邢台市'), ('保定市', '保定市'), ('张家口市', '张家口市'), ('承德市', '承德市'), ('沧州市', '沧州市'), ('廊坊市', '廊坊市'), ('衡水市', '衡水市'), ('雄安新区', '雄安新区'), ('不区分', '不区分')], max_length=100)),
                ('qdate', models.DateTimeField(auto_now_add=True)),
                ('qmethod', models.CharField(choices=[('电话', '电话'), ('微信/QQ', '微信/QQ'), ('邮件', '邮件')], max_length=20)),
                ('question', models.TextField(max_length=200)),
                ('process', models.TextField(max_length=200)),
                ('result', models.CharField(choices=[('正在处理', '正在处理'), ('处理完成', '处理完成'), ('挂起', '挂起')], max_length=20)),
                ('limit', models.IntegerField()),
                ('spending', models.IntegerField()),
                ('recorder', models.CharField(max_length=10)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ops.Engineer', verbose_name='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ops.Project')),
            ],
            options={
                'verbose_name': '记录清单',
                'verbose_name_plural': '记录清单',
            },
        ),
    ]
