# Generated by Django 3.0.7 on 2020-06-30 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0002_auto_20200630_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opsrecord',
            name='qdate',
            field=models.DateTimeField(verbose_name='致电时间'),
        ),
        migrations.AlterField(
            model_name='opsrecord',
            name='spending',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='实际处理时长(h)'),
        ),
    ]
