# Generated by Django 3.0.7 on 2020-06-30 02:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0003_auto_20200630_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opsrecord',
            name='qdate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='致电(发现)时间'),
        ),
        migrations.AlterField(
            model_name='opsrecord',
            name='qmethod',
            field=models.CharField(blank=True, choices=[('电话', '电话'), ('微信/QQ', '微信/QQ'), ('邮件', '邮件')], max_length=20, null=True, verbose_name='致电方式'),
        ),
    ]
