# Generated by Django 3.0.7 on 2020-06-30 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ops', '0005_auto_20200630_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opsrecord',
            name='recorder',
        ),
        migrations.AlterField(
            model_name='opsrecord',
            name='engineer',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='工程师'),
        ),
        migrations.DeleteModel(
            name='Engineer',
        ),
    ]
