"""
Django settings for myweb project.

Generated by 'django-admin startproject' using Django 3.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'f8_e#sh=gcn@%5xh2cuje(@m!fhnv#5yv(4m97t$fhzrt(-vdk'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ops',
    'cmdb',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myweb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myweb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "static")
SIMPLEUI_STATIC_OFFLINE = True
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, "static")
# ]

SIMPLEUI_DEFAULT_THEME = 'ant.design.css'

SIMPLEUI_HOME_INFO = False
SIMPLEUI_HOME_QUICK = False
SIMPLEUI_HOME_ACTION = False
SIMPLEUI_ANALYSIS = False


SIMPLEUI_CONFIG = {
    'system_keep': False,
    'menu_display': ['关联文档', '基础环境', '虚拟IT资产', '实体IT资产', '数据字典', '日常运维', '权限认证'],
    'dynamic': True,
    'menus': [{
        'app': 'cmdb',
        'name': '关联文档',
        'icon': 'fas fa-file-pdf',
        'models': [{
                'name': '项目列表',
                'icon': 'fa fa-chevron-circle-right',
                'url': 'cmdb/project/'
            },
            {
                'name': '合同列表',
                'icon': 'fa fa-chevron-circle-right',
                'url': 'cmdb/contract/'
            },
            {
                'name': '厂商和供货商',
                'icon': 'fa fa-chevron-circle-right',
                'url': 'cmdb/supplier/'
            }, ]
    }, {
        'app': 'cmdb',
        'name': '基础环境',
        'icon': 'fas fa-power-off',
        'models': [{
                'name': '机房列表',
                'icon': 'fa fa-chevron-circle-right',
                'url': 'cmdb/datacenter/'
            },
            {
                'name': '机柜列表',
                'icon': 'fa fa-chevron-circle-right',
                'url': 'cmdb/rack/'
            },
            {
                'name': '风火水电',
                'icon': 'fa fa-chevron-circle-right',
                'url': 'cmdb/fhsd/'
            }, ]
    }, {
        'app': 'cmdb',
        'name': '虚拟IT资产',
        'icon': 'fas fa-database',
        'models': [
            {
                'name': '业务列表',
                'icon': 'fa fa-chevron-circle-right',
                'url': 'cmdb/production/'
            },
            {
                'name': '数字资产',
                'icon': 'fa fa-chevron-circle-right',
                'url': 'cmdb/digitalasset/'
            },
            {
                'name': '虚拟机',
                'icon': 'fa fa-chevron-circle-right',
                'url': 'cmdb/virtualserver/'
            },
            {
                'name': '虚拟接口',
                'icon': 'fa fa-chevron-circle-right',
                'url': 'cmdb/virtualinterface/'
            }, ]
    }, {
        'app': 'cmdb',
        'name': '实体IT资产',
        'icon': 'fas fa-save',
        'models': [{
                'name': '服务器',
                'icon': 'fa fa-chevron-circle-right',
                'url': 'cmdb/server/'
            },
            {
                'name': '存储设备',
                'icon': 'fa fa-chevron-circle-right',
                'url': 'cmdb/storage/'
            },
            {
                'name': '网络设备',
                'icon': 'fa fa-chevron-circle-right',
                'url': 'cmdb/switch/'
            },
            {
                'name': '安全设备',
                'icon': 'fa fa-chevron-circle-right',
                'url': 'cmdb/security/'
            },
            {
                'name': '网络接口',
                'icon': 'fa fa-chevron-circle-right',
                'url': 'cmdb/interface/'
            },
            {
                'name': '办公设备',
                'icon': 'fa fa-chevron-circle-right',
                'url': 'cmdb/officedevice/'
            },
            {
                'name': '终端设备',
                'icon': 'fa fa-chevron-circle-right',
                'url': 'cmdb/endpointdevice/'
            },
            {
                'name': '专线线路',
                'icon': 'fa fa-chevron-circle-right',
                'url': 'cmdb/lines/'
            },
        ]
    }, {
        'app': 'cmdb',
        'name': '数据字典',
        'icon': 'fas fa-file-word',
        'models': [{
                'name': '地市字典',
                'icon': 'fa fa-chevron-circle-right',
                'url': 'cmdb/city/'
            },
            {
                'name': '资产类型字典',
                'icon': 'fa fa-chevron-circle-right',
                'url': 'cmdb/assettype/'
            },
            {
                'name': '安全设备字典',
                'icon': 'fa fa-chevron-circle-right',
                'url': 'cmdb/safetytype/'
            },
            {
                'name': '基础环境字典',
                'icon': 'fa fa-chevron-circle-right',
                'url': 'cmdb/fhsds/'
            },
            {
                'name': '办公设备字典',
                'icon': 'fa fa-chevron-circle-right',
                'url': 'cmdb/officedev/'
            },
            {
                'name': '终端设备字典',
                'icon': 'fa fa-chevron-circle-right',
                'url': 'cmdb/eps/'
            },
        ]
    }, {
        'app': 'ops',
        'name': '日常运维',
        'icon': 'fas fa-gavel',
        'models': [{
            'name': '运维记录',
            'icon': 'fa fa-chevron-circle-right',
            'url': 'ops/opsrecord/'
        }]
    }, {
        'app': 'auth',
        'name': '权限认证',
        'icon': 'fas fa-user-shield',
        'models': [{
            'name': '用户',
            'icon': 'fa fa-chevron-circle-right',
            'url': 'auth/user/'
        },
            {
                'name': '组',
                'icon': 'fa fa-chevron-circle-right',
                'url': 'auth/group/'
            }
        ]
    }
    ]
}
